-- Run this once in the Supabase SQL editor.
-- Full workout data is owner-only. Friends can query workout and exercise-name overviews only.
-- The global leaderboard exposes display names and aggregate totals, never raw sets.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  friend_code text not null unique check (friend_code ~ '^[A-Z0-9]{6,12}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Personal measurements are separated from discoverable profiles so friends
-- and leaderboard users can never read them through the profiles API.
create table if not exists public.profile_details (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  first_name text not null check (char_length(btrim(first_name)) between 1 and 60),
  last_name text not null check (char_length(btrim(last_name)) between 1 and 60),
  age smallint not null check (age between 13 and 120),
  gender text not null check (gender in ('male', 'female', 'non_binary', 'other', 'prefer_not_to_say')),
  weight_kg numeric(6,2) not null check (weight_kg between 20 and 500),
  height_cm numeric(5,2) not null check (height_cm between 80 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_states (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);

create unique index if not exists friendships_unique_pair
  on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friendships_requester_status on public.friendships (requester_id, status);
create index if not exists friendships_addressee_status on public.friendships (addressee_id, status);
create index if not exists profiles_display_name_lower_pattern
  on public.profiles (lower(display_name) text_pattern_ops);

create table if not exists public.workout_overviews (
  id text primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  workout_name text not null check (char_length(workout_name) between 1 and 80),
  started_at timestamptz not null,
  duration_ms bigint not null default 0 check (duration_ms >= 0),
  exercise_count integer not null default 0 check (exercise_count >= 0),
  total_sets integer not null default 0 check (total_sets >= 0),
  total_volume numeric not null default 0 check (total_volume >= 0),
  workout_date date not null,
  units text not null default 'kg' check (units in ('kg','lbs')),
  exercise_names text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);
alter table public.workout_overviews add column if not exists total_volume numeric not null default 0 check (total_volume >= 0);
alter table public.workout_overviews add column if not exists workout_date date;
alter table public.workout_overviews add column if not exists exercise_names text[] not null default '{}'::text[];
update public.workout_overviews set workout_date=(started_at at time zone 'UTC')::date where workout_date is null;
alter table public.workout_overviews alter column workout_date set not null;
create index if not exists workout_overviews_user_started on public.workout_overviews (user_id, started_at desc);

alter table public.profiles enable row level security;
alter table public.profile_details enable row level security;
alter table public.user_states enable row level security;
alter table public.friendships enable row level security;
alter table public.workout_overviews enable row level security;

grant select, insert, update on table public.profiles to authenticated;
revoke all on table public.profile_details from anon;
revoke all on table public.profile_details from authenticated;
grant select, insert, update on table public.profile_details to authenticated;
grant select, insert, update on table public.user_states to authenticated;
grant select, insert, update, delete on table public.friendships to authenticated;
grant select, insert, update, delete on table public.workout_overviews to authenticated;
grant usage, select on sequence public.friendships_id_seq to authenticated;

drop policy if exists "authenticated profiles are discoverable" on public.profiles;
drop policy if exists "users see connected profiles" on public.profiles;
create policy "users see connected profiles" on public.profiles
  for select to authenticated using (
    id = (select auth.uid()) or exists (
      select 1 from public.friendships f
      where (f.requester_id = (select auth.uid()) and f.addressee_id = profiles.id)
         or (f.addressee_id = (select auth.uid()) and f.requester_id = profiles.id)
    )
  );
drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles
  for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles
  for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "owners read profile details" on public.profile_details;
create policy "owners read profile details" on public.profile_details
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "owners insert profile details" on public.profile_details;
create policy "owners insert profile details" on public.profile_details
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "owners update profile details" on public.profile_details;
create policy "owners update profile details" on public.profile_details
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "owners read private state" on public.user_states;
create policy "owners read private state" on public.user_states
  for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "owners insert private state" on public.user_states;
create policy "owners insert private state" on public.user_states
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "owners update private state" on public.user_states;
create policy "owners update private state" on public.user_states
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "owners delete private state" on public.user_states;
create policy "owners delete private state" on public.user_states
  for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "participants read friendships" on public.friendships;
create policy "participants read friendships" on public.friendships
  for select to authenticated using ((select auth.uid()) in (requester_id, addressee_id));
drop policy if exists "users send requests" on public.friendships;
create policy "users send requests" on public.friendships
  for insert to authenticated with check ((select auth.uid()) = requester_id and status = 'pending');
drop policy if exists "recipients accept requests" on public.friendships;
create policy "recipients accept requests" on public.friendships
  for update to authenticated
  using ((select auth.uid()) = addressee_id and status = 'pending')
  with check ((select auth.uid()) = addressee_id and status = 'accepted');
drop policy if exists "participants remove friendships" on public.friendships;
create policy "participants remove friendships" on public.friendships
  for delete to authenticated using ((select auth.uid()) in (requester_id, addressee_id));

drop policy if exists "owners and friends read overviews" on public.workout_overviews;
create policy "owners and friends read overviews" on public.workout_overviews
  for select to authenticated using (
    user_id = (select auth.uid()) or exists (
      select 1 from public.friendships f
      where f.status = 'accepted' and (
        (f.requester_id = (select auth.uid()) and f.addressee_id = workout_overviews.user_id) or
        (f.addressee_id = (select auth.uid()) and f.requester_id = workout_overviews.user_id)
      )
    )
  );
drop policy if exists "owners insert overviews" on public.workout_overviews;
create policy "owners insert overviews" on public.workout_overviews
  for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "owners update overviews" on public.workout_overviews;
create policy "owners update overviews" on public.workout_overviews
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "owners delete overviews" on public.workout_overviews;
create policy "owners delete overviews" on public.workout_overviews
  for delete to authenticated using ((select auth.uid()) = user_id);

create or replace function public.friend_leaderboard(range_start timestamptz default null)
returns table (
  user_id uuid,
  workout_days bigint,
  workout_count bigint,
  total_sets bigint,
  total_volume_kg numeric
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    o.user_id,
    count(distinct o.workout_date) as workout_days,
    count(*) as workout_count,
    sum(o.total_sets)::bigint as total_sets,
    round(sum(case when o.units = 'lbs' then o.total_volume * 0.45359237 else o.total_volume end), 2) as total_volume_kg
  from public.workout_overviews o
  where range_start is null or o.started_at >= range_start
  group by o.user_id;
$$;
revoke all on function public.friend_leaderboard(timestamptz) from public;
revoke all on function public.friend_leaderboard(timestamptz) from anon;
grant execute on function public.friend_leaderboard(timestamptz) to authenticated;

drop function if exists public.global_leaderboard(timestamptz);
create or replace function public.global_leaderboard(leader_period text default 'all')
returns table (
  user_id uuid,
  display_name text,
  workout_days bigint,
  workout_count bigint,
  total_sets bigint,
  total_volume_kg numeric
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  period_start timestamptz;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if leader_period not in ('week', 'month', 'year', 'all') then
    raise exception 'Unsupported leaderboard period' using errcode = '22023';
  end if;

  period_start := case leader_period
    when 'week' then date_trunc('day', now()) - extract(dow from now()) * interval '1 day'
    when 'month' then date_trunc('month', now())
    when 'year' then date_trunc('year', now())
    else null
  end;

  return query
  select
    p.id,
    p.display_name,
    count(distinct o.workout_date) as workout_days,
    count(o.id) as workout_count,
    coalesce(sum(o.total_sets), 0)::bigint as total_sets,
    round(
      coalesce(
        sum(
          case
            when o.units = 'lbs' then o.total_volume * 0.45359237
            else o.total_volume
          end
        ),
        0
      ),
      2
    ) as total_volume_kg
  from public.profiles p
  left join public.workout_overviews o
    on o.user_id = p.id
   and (period_start is null or o.started_at >= period_start)
  group by p.id, p.display_name;
end;
$$;
revoke all on function public.global_leaderboard(text) from public;
revoke all on function public.global_leaderboard(text) from anon;
grant execute on function public.global_leaderboard(text) to authenticated;

create or replace function public.find_profile_by_friend_code(search_code text)
returns table (id uuid, display_name text)
language sql
stable
security definer set search_path = ''
as $$
  select p.id, p.display_name
  from public.profiles p
  where (select auth.uid()) is not null
    and p.friend_code = upper(trim(search_code))
  limit 1;
$$;
revoke all on function public.find_profile_by_friend_code(text) from public;
revoke all on function public.find_profile_by_friend_code(text) from anon;
grant execute on function public.find_profile_by_friend_code(text) to authenticated;

create or replace function public.search_profiles_by_name(search_term text)
returns table (id uuid, display_name text)
language sql
stable
security definer
set search_path = ''
as $$
  select p.id, p.display_name
  from public.profiles p
  where (select auth.uid()) is not null
    and p.id <> (select auth.uid())
    and char_length(btrim(search_term)) between 2 and 80
    and btrim(search_term) !~ '[%_]'
    and lower(p.display_name) like lower(btrim(search_term)) || '%'
  order by
    case when lower(p.display_name) = lower(btrim(search_term)) then 0 else 1 end,
    lower(p.display_name),
    p.id
  limit 10;
$$;
revoke all on function public.search_profiles_by_name(text) from public;
revoke all on function public.search_profiles_by_name(text) from anon;
grant execute on function public.search_profiles_by_name(text) to authenticated;

create or replace function public.make_profile_for_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, friend_code)
  values (
    new.id,
    left(coalesce(nullif(new.raw_user_meta_data ->> 'display_name',''), split_part(new.email,'@',1), 'Lifter'), 80),
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  );
  return new;
end;
$$;
revoke all on function public.make_profile_for_new_user() from public;
revoke all on function public.make_profile_for_new_user() from anon;
revoke all on function public.make_profile_for_new_user() from authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.make_profile_for_new_user();
